#测试数据库配置信息
jdbc:
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://localhost:1433;DatabaseName=ksoa
  username: sa
  password: scm123


rmk:
  clientId : fc3dfedc4d34b4f06d13d3e0b0f6cb96
  clientSecret: 28aec98630e6663924a504d253afd7a8
  branchId : hbhzyp
  customerUrl: https://test-runapi.medi-care.com.cn/v1/msg/customer
  productUrl: https://test-runapi.medi-care.com.cn/v1/msg/product
  orderGetUrl: https://test-runapi.medi-care.com.cn/v1/open/orderGrab
  orderMarkUrl: https://test-runapi.medi-care.com.cn/v1/open/orderMark
  orderStatusUrl: https://test-runapi.medi-care.com.cn/v1/msg/order